app:
  kafka:
    partitions: 1
    replicas: 1
    topics:
      github-provisioning: edu.provisioning.github.v1
      atlassian-provisioning: edu.provisioning.atlassian.v1
      github-provisioning-dlt: edu.provisioning.github.v1.DLT
      atlassian-provisioning-dlt: edu.provisioning.atlassian.v1.DLT
  open-api:
    description: '@project.description@'
    title: '@project.name@'
    version: '@project.version@'
spring:
  application:
    name: provisioning-service
  datasource:
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:provisioning_service}
    username: ${DATABASE_USER:default}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  flyway:
    enabled: true
  kafka:
    producer:
      retries: 10
      acks: all
      properties:
        delivery:
          timeout: 60000
        request:
          timeout:
            ms: 30000
        linger:
          ms: 0
        max:
          inflight:
            requests:
              per:
                connection: 5
        enable:
          idempotence: true
    bootstrap-servers: ${BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:9090}
    consumer:
      group-id: provisioning-service
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
  profiles:
    active: dev
management:
  endpoint:
    health:
      probes:
        enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}
github:
  api:
    base-url: https://api.github.com
    token: ${GITHUB_API_TOKEN}
    org: ${GITHUB_ORG}
atlassian:
  api:
    base-url: ${ATLASSIAN_API_BASE_URL}
    email: ${ATLASSIAN_API_EMAIL}
    token: ${ATLASSIAN_API_TOKEN}
jwt:
  secret: ${JWT_SECRET}
  issuer: ${spring.application.name}
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
