server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
logging:
  level:
    root: info
    xyz:
      catuns:
        onboarding:
          user: debug
jwt:
  security:
    public-paths: /swagger-ui/**, /v3/api-docs/**, /actuator/health/**, /error/**, /**