spring:
  cloud:
    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        prefer-ip-address: false
        hostname: ${spring.application.name}
server:
  port: 8080
logging:
  level:
    root: warn
    xyz:
      catuns:
        onboarding:
          apigateway: info
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}