spring:
  cloud:
    consul:
      host: consul
server:
  port: 8080
logging:
  level:
    root: warn
    xyz:
      catuns:
        onboarding:
          apigateway: info
management:
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_ENDPOINT:http://zipkin:9411/api/v2/spans}