server:
  port: 8082
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: false
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  level:
    root: info
    xyz:
      catuns:
        onboarding:
          service: debug
